name: example
version: 0.0.1
homepage: https://github.com/rrousselGit/flutter_portal
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_portal:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
