name: flutter_portal
version: 0.0.1
description: Overlay/OverlayEntry, but declarative
homepage: https://github.com/rrousselGit/flutter_portal
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
